# Generated by Django 5.2.5 on 2026-01-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.CharField(blank=True, default='ENSAE Dakar', max_length=50, null=True),
        ),
    ]
