"""
Django settings for noxa project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
import cloudinary
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-8#-vp#m#wl*7@5)v6$x9hy-_bpg80axt1p$(hmc5x__nhvvnx5')

DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.railway.app']

# CSRF settings for Railway
CSRF_TRUSTED_ORIGINS = ['https://*.railway.app', 'https://noxa-production.up.railway.app']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base.apps.BaseConfig',
    'chat.apps.ChatConfig',  # App Chatbot RAG
    'cloudinary_storage',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'noxa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'Templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.notifications_context',
                'base.context_processors.recentSearches',
            ],
        },
    },
]

WSGI_APPLICATION = 'noxa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databasess

# Database configuration
# Railway provide DATABASE_URL by We use Neon as fallback for production.
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', ''),
        conn_max_age=600,
        conn_health_checks=True
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validatorss

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'Static',
]

# WhiteNoise configuration
# (Note: In Django 4.2+, prefer using the STORAGES setting below)

# Define the user model
AUTH_USER_MODEL = 'base.CustomUser' # 'auth.User' by default

# Login URL
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'  # Redirect to home after login
LOGOUT_REDIRECT_URL = '/login/'  # Redirect to login after logout

# Media files
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# Modern Django 4.2+ Storage configuration
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
    api_key=os.getenv('CLOUDINARY_API_KEY'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET'),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-fiel

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# OpenAI API
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# HuggingFace
HF_TOKEN = os.getenv('HF_TOKEN', None)

# Pinecone
PINECONE_API_KEY = os.getenv('PINECONE_API_KEY', None)
PINECONE_INDEX_NAME = os.getenv('PINECONE_INDEX_NAME', 'rag-test2')
PINECONE_EMBED_MODEL = os.getenv('PINECONE_EMBED_MODEL', 'multilingual-e5-large')
PINECONE_RERANK_MODEL = os.getenv('PINECONE_RERANK_MODEL', 'bge-reranker-v2-m3')
PINECONE_NAMESPACE = os.getenv('PINECONE_NAMESPACE', '__default__')

# LLM
LLM_MODEL = os.getenv('LLM_MODEL', 'meta-llama/Llama-3.1-8B-Instruct')
LLM_TEMPERATURE = float(os.getenv('LLM_TEMPERATURE', '0.7'))
LLM_MAX_TOKENS = int(os.getenv('LLM_MAX_TOKENS', '1000'))

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'rag_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'rag.log',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'services.rag': {
            'handlers': ['rag_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'services.document_processing': {
            'handlers': ['rag_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "NOXA Admin",
    "site_header": "NOXA",
    "site_brand": "NOXA Admin",
    "welcome_sign": "Bienvenue sur l'administration de NOXA",
    "copyright": "NOXA AI",
    "search_model": ["auth.User", "base.Publication"],
    
    # UI Customization
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Chat", "url": "/chat/", "new_window": True},
    ],
    
    # Navigation Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "base.Publication": "fas fa-file-pdf",
        "base.DocumentChunk": "fas fa-layer-group",
        "base.Collection": "fas fa-folder",
        "chat.Conversation": "fas fa-comments",
        "chat.Message": "fas fa-comment-dots",
    },
    
    # Order of usage
    "order_with_respect_to": ["chat", "base", "auth"],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "dark_mode_theme": "darkly",
}
