# Generated by Django 5.2.5 on 2026-02-09 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant'), ('system', 'Système')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_embedding_time', models.FloatField(blank=True, help_text="Temps pour générer l'embedding (ms)", null=True)),
                ('retrieval_time', models.FloatField(blank=True, help_text='Temps de récupération des documents (ms)', null=True)),
                ('generation_time', models.FloatField(blank=True, help_text='Temps de génération de la réponse (ms)', null=True)),
                ('total_time', models.FloatField(blank=True, help_text='Temps total de traitement (ms)', null=True)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées extraites (questions suivies, images citées, etc.)')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Très mauvais'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Excellent')], null=True)),
                ('issue_type', models.CharField(blank=True, choices=[('irrelevant', 'Réponse non pertinente'), ('incorrect', 'Information incorrecte'), ('incomplete', 'Réponse incomplète'), ('unclear', 'Réponse pas claire'), ('sources_wrong', 'Mauvaises sources citées'), ('other', 'Autre')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_feedback', to='chat.chatmessage')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_attachments/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='ChatSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Index du chunk utilisé dans le document')),
                ('relevance_score', models.FloatField(help_text='Score de similarité (0-1)')),
                ('excerpt', models.TextField(help_text='Extrait du texte utilisé comme contexte')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_references', to='chat.chatattachment')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='chat.chatmessage')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_references', to='base.publication')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(blank=True, help_text='Topic spécifique pour cibler les réponses du RAG', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
    ]
